// Front-end account prototype. Real authentication requires a server/backend.
function escapeHTML(value){return String(value??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
function getPlaybaseUser(){ try { return JSON.parse(localStorage.getItem('playbase-user') || 'null'); } catch(e){ return null; } }
function syncAccountButton(){
  const user=getPlaybaseUser(), btn=document.getElementById('accountCta'), mobile=document.getElementById('mobileAccountLink');
  if(btn){btn.href=user?'#/panel':'#/login';btn.innerHTML=user?`<span class="account-avatar">${(user.name||user.email||'P').charAt(0).toUpperCase()}</span> ${escapeHTML((user.name||'My account').split(' ')[0])}`:'Log in <span>↗</span>';}
  if(mobile){mobile.href=user?'#/panel':'#/login';mobile.innerHTML=`<span class="mobile-label"><span class="mi">◉</span>${user?'My account':'Log in / Account'}</span>`;}
}
function renderLogin(){
  const user=getPlaybaseUser(); if(user){location.hash='#/panel';return;}
  view.innerHTML=`<section class="account-page"><div class="account-orbit orbit-one"></div><div class="account-orbit orbit-two"></div><div class="login-layout"><div class="login-story"><div class="account-kicker"><span class="status-dot"></span> YOUR GAME LIBRARY, CONNECTED</div><h1>Welcome back to<br><span>your next adventure.</span></h1><p>Sign in to keep your wishlist close, track the games you love and make your Playbase experience yours.</p><div class="login-feature-list"><div><span class="feature-icon">♡</span><span><b>Your wishlist</b><small>Keep every game you want in one place.</small></span></div><div><span class="feature-icon">↗</span><span><b>Personal dashboard</b><small>Pick up where you left off.</small></span></div><div><span class="feature-icon">⌁</span><span><b>Game discovery</b><small>Find your next favorite faster.</small></span></div></div></div><div class="login-card"><a class="login-brand" href="#/"><span class="login-brand-mark">P</span><span>Playbase</span></a><div class="login-card-heading"><h2>Log in</h2><p>Enter your details to access your account.</p></div><form id="loginForm" class="account-form"><label for="loginEmail">Email address</label><input id="loginEmail" type="email" placeholder="you@example.com" autocomplete="email" required><div class="password-label"><label for="loginPassword">Password</label><a href="#/login" id="forgotPassword">Forgot password?</a></div><div class="password-wrap"><input id="loginPassword" type="password" placeholder="Enter your password" autocomplete="current-password" minlength="4" required><button type="button" class="password-toggle" id="togglePassword" aria-label="Show password">Show</button></div><div class="login-error" id="loginError" role="alert"></div><button class="account-submit" type="submit">Continue <span>→</span></button></form><div class="account-divider"><span></span> NEW TO PLAYBASE? <span></span></div><button class="account-secondary" id="createAccount">Create an account</button><p class="account-legal">By continuing, you agree to our <a href="#/">Terms</a> and <a href="#/">Privacy Policy</a>.</p><p class="prototype-note">Prototype mode: this demo stores a local profile in this browser only.</p></div></div></section>`;
  document.getElementById('togglePassword').onclick=()=>{const i=document.getElementById('loginPassword');const show=i.type==='password';i.type=show?'text':'password';document.getElementById('togglePassword').textContent=show?'Hide':'Show';};
  document.getElementById('forgotPassword').onclick=(e)=>{e.preventDefault();document.getElementById('loginError').textContent='Password reset will be available when account services are connected.';};
  document.getElementById('createAccount').onclick=()=>{location.hash='#/signup';};
  document.getElementById('loginForm').onsubmit=(e)=>{e.preventDefault();const email=document.getElementById('loginEmail').value.trim();const password=document.getElementById('loginPassword').value; if(password.length<4){document.getElementById('loginError').textContent='Use at least 4 characters for this prototype.';return;}const name=(email.split('@')[0]||'Player').replace(/[._-]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase());localStorage.setItem('playbase-user',JSON.stringify({name,email,joined:new Date().toISOString()}));syncAccountButton();location.hash='#/panel';};
  syncAccountButton();
}
function renderSignup(){
  if(getPlaybaseUser()){location.hash='#/panel';return;}
  view.innerHTML=`<section class="account-page signup-page"><div class="account-orbit orbit-one"></div><div class="account-orbit orbit-two"></div><div class="signup-wrap"><div class="signup-intro"><a class="login-brand" href="#/"><span class="login-brand-mark">P</span><span>Playbase</span></a><span class="account-kicker"><span class="status-dot"></span> JOIN THE COMMUNITY</span><h1>Create your<br><span>Playbase account.</span></h1><p>Build your wishlist, keep track of games you love and make your discovery experience personal.</p><a class="signup-back" href="#/login">← Already have an account? Log in</a></div><div class="login-card signup-card"><div class="login-card-heading"><h2>Create account</h2><p>Enter your details to get started.</p></div><form id="signupForm" class="account-form"><label for="signupName">Full name</label><input id="signupName" type="text" placeholder="Your name" autocomplete="name" minlength="2" required><label for="signupEmail">Email address</label><input id="signupEmail" type="email" placeholder="you@example.com" autocomplete="email" required><label for="signupPassword">Password</label><input id="signupPassword" type="password" placeholder="At least 4 characters" autocomplete="new-password" minlength="4" required><label for="signupConfirm">Confirm password</label><input id="signupConfirm" type="password" placeholder="Repeat your password" autocomplete="new-password" minlength="4" required><div class="login-error" id="signupError" role="alert"></div><button class="account-submit" type="submit">Create account <span>→</span></button></form><p class="account-legal">By creating an account, you agree to our <a href="#/">Terms</a> and <a href="#/">Privacy Policy</a>.</p><p class="prototype-note">Demo mode: this profile is saved only in this browser.</p></div></div></section>`;
  document.getElementById('signupForm').onsubmit=e=>{e.preventDefault();const name=document.getElementById('signupName').value.trim();const email=document.getElementById('signupEmail').value.trim();const password=document.getElementById('signupPassword').value;const confirm=document.getElementById('signupConfirm').value;const error=document.getElementById('signupError');if(password.length<4){error.textContent='Password must contain at least 4 characters.';return;}if(password!==confirm){error.textContent='Passwords do not match.';return;}localStorage.setItem('playbase-user',JSON.stringify({name,email,joined:new Date().toISOString()}));localStorage.setItem('playbase-demo-password',password);syncAccountButton();location.hash='#/panel';};
  syncAccountButton();
}

function renderAccountPanel(){
 const user=getPlaybaseUser();if(!user){location.hash='#/login';return;}
 const initials=(user.name||user.email).charAt(0).toUpperCase();
 view.innerHTML=`<section class="panel-page"><div class="panel-shell"><aside class="panel-sidebar"><a class="panel-brand" href="#/"><span class="login-brand-mark">P</span><span>Playbase <small>PLAYER SPACE</small></span></a><div class="panel-user-mini"><span class="panel-avatar">${initials}</span><span><b>${escapeHTML(user.name||'Player')}</b><small>${escapeHTML(user.email)}</small></span></div><div class="panel-nav-label">WORKSPACE</div><button class="panel-nav active" data-panel="overview"><span>▦</span> Overview</button><button class="panel-nav" data-panel="wishlist"><span>♡</span> Wishlist <i>0</i></button><button class="panel-nav" data-panel="recent"><span>◷</span> Recently viewed</button><div class="panel-nav-label">PREFERENCES</div><button class="panel-nav" data-panel="settings"><span>⚙</span> Account settings</button><div class="panel-sidebar-bottom"><a href="#/browse">← Explore games</a><button id="logoutButton"><span>↗</span> Log out</button></div></aside><div class="panel-main"><header class="panel-topbar"><div><span class="panel-breadcrumb">PLAYER SPACE / <b id="panelCrumb">OVERVIEW</b></span><h1 id="panelTitle">Your dashboard</h1></div><a class="panel-explore" href="#/browse">Explore games <span>↗</span></a></header><div id="panelContent"></div></div></div></section>`;
 const content=document.getElementById('panelContent');
 function showPanel(tab){document.querySelectorAll('.panel-nav[data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===tab));const titles={overview:'Your dashboard',wishlist:'Your wishlist',recent:'Recently viewed',settings:'Account settings'};document.getElementById('panelTitle').textContent=titles[tab];document.getElementById('panelCrumb').textContent=tab.toUpperCase();
 if(tab==='overview') content.innerHTML=`<div class="panel-welcome"><div><span class="account-kicker"><span class="status-dot"></span> PLAYER OVERVIEW</span><h2>Good to see you, ${escapeHTML((user.name||'Player').split(' ')[0])}.</h2><p>Your personal space for everything you want to play next.</p></div><div class="welcome-mark">P<span>+</span></div></div><div class="panel-stats"><div class="panel-stat-card"><span>WISHLISTED GAMES</span><b>0</b><small>Build your next-play list</small><i>♡</i></div><div class="panel-stat-card"><span>RECENTLY VIEWED</span><b>0</b><small>Your browsing history</small><i>◷</i></div><div class="panel-stat-card"><span>ACCOUNT STATUS</span><b class="status-active">Active</b><small>Profile ready to personalize</small><i>✓</i></div></div><div class="panel-lower-grid"><div class="panel-box"><div class="panel-box-heading"><div><span class="panel-eyebrow">GET STARTED</span><h3>Make Playbase yours</h3></div><span class="panel-heading-icon">✦</span></div><a class="panel-action-row" href="#/browse"><span class="panel-action-icon">⌕</span><span><b>Discover games</b><small>Browse the catalog and find something new.</small></span><strong>→</strong></a><button class="panel-action-row panel-action-button" data-panel="wishlist"><span class="panel-action-icon">♡</span><span><b>Build your wishlist</b><small>Keep track of games you want to play.</small></span><strong>→</strong></button></div><div class="panel-box account-summary"><span class="panel-eyebrow">YOUR PROFILE</span><div class="summary-profile"><span class="panel-avatar large">${initials}</span><div><b>${escapeHTML(user.name||'Player')}</b><small>${escapeHTML(user.email)}</small></div></div><div class="summary-line"><span>Member since</span><b>${new Date(user.joined||Date.now()).toLocaleDateString(undefined,{month:'short',year:'numeric'})}</b></div><button class="summary-edit" data-panel="settings">Edit profile <span>→</span></button></div></div>`;
 else if(tab==='wishlist') content.innerHTML=`<div class="panel-empty"><span>♡</span><h2>Your wishlist starts here</h2><p>Save games from the catalog to build a list of titles you want to play. Wishlist syncing will be connected when the backend is added.</p><a class="account-submit inline-submit" href="#/browse">Browse games →</a></div>`;
 else if(tab==='recent') content.innerHTML=`<div class="panel-empty"><span>◷</span><h2>No games viewed yet</h2><p>Games you visit will be available here once browsing history is connected.</p><a class="account-submit inline-submit" href="#/browse">Explore games →</a></div>`;
 else content.innerHTML=`<div class="panel-settings"><div class="panel-box"><span class="panel-eyebrow">PERSONAL INFORMATION</span><h3>Profile details</h3><form id="profileForm" class="account-form settings-form"><label for="profileName">Display name</label><input id="profileName" value="${escapeHTML(user.name||'')}" required><label for="profileEmail">Email address</label><input id="profileEmail" type="email" value="${escapeHTML(user.email||'')}" required><button class="account-submit" type="submit">Save changes <span>→</span></button><p class="settings-feedback" id="settingsFeedback"></p></form></div><div class="panel-box"><span class="panel-eyebrow">SESSION</span><h3>Local demo account</h3><p class="settings-description">This prototype keeps profile data in this browser only. It is not a secure account system and does not sync between devices.</p><button class="account-secondary danger-secondary" id="settingsLogout">Log out of this browser</button></div></div>`;
 content.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>showPanel(b.dataset.panel));const pf=document.getElementById('profileForm');if(pf)pf.onsubmit=e=>{e.preventDefault();user.name=document.getElementById('profileName').value.trim();user.email=document.getElementById('profileEmail').value.trim();localStorage.setItem('playbase-user',JSON.stringify(user));syncAccountButton();document.getElementById('settingsFeedback').textContent='Profile updated in this browser.';};document.getElementById('settingsLogout')?.addEventListener('click',logout);}
 function logout(){localStorage.removeItem('playbase-user');syncAccountButton();location.hash='#/';}
 document.querySelectorAll('.panel-nav[data-panel]').forEach(b=>b.onclick=()=>showPanel(b.dataset.panel));document.getElementById('logoutButton').onclick=logout;showPanel('overview');syncAccountButton();
}
window.addEventListener('hashchange',syncAccountButton);
